### ISSUE TITLE
hover dataset

### ISSUE THREAD

**Issue by dependentsign** [Cartus/Automated-Fact-Checking-Literature#3]
I guess the hover dataset verdict should be 
<img width="579" alt="Screen Shot 2022-04-19 at 21 23 05" src="https://user-images.githubusercontent.com/59330230/164013878-cf44a0b7-aea3-4ea6-90ea-ce708088d0a9.png">
targed as two classes

**Comment by Cartus** [comment]
Thank you so much for pointing this out! We will modify our paper accordingly.
